--this script initiates db for h2 db (used in test profile)
insert into user (id, account_status, email, first_name, last_name) values (null, 'CONFIRMED', 'john@domain.com', 'John', 'Steward')
insert into user (id, account_status, email, first_name) values (null, 'NEW', 'brian@domain.com', 'Brian')
insert into user (id, account_status, email, first_name, last_name) values (null, 'CONFIRMED', 'jacob@domain.com', 'Jacob', 'Steward')
insert into user (id, account_status, email, first_name, last_name) values (null, 'REMOVED', 'walter@domain.com', 'Walter', 'White')
insert into user (id, account_status, email, first_name, last_name) values (null, 'CONFIRMED', 'Skyler@domain.com', 'Skyler', 'White')
